### ISSUE TITLE
Implement Folder/File links in IDB.Translate.BCP

### ISSUE THREAD

**Issue by kieninj** [coolOrangeLabs/powerload-utilities#16]

**Comment by MarkusCool** [comment]
In Vault it is possible to link a file to an folder. this is often used, when folders are representing projects and a file is used in multiple projects.
![FolderFileLinks](https://user-images.githubusercontent.com/36193155/186160245-75e23ac7-a51e-44ac-8b41-1c13f3658d53.png)

The intermediate database (IDB) has a table 'FolderFileLinks' with 'ParentFolderID' and 'ChildFileID'.
When this is filled, the IDB.Translate.BCP must create a link in the Vault.xml with the TargetID of the flie in the folder section, by using the bcpToolkit:
![FolderFileLink_bcp](https://user-images.githubusercontent.com/36193155/186162006-758bc58e-377e-4cf5-bbac-317ebba0909f.png)

Attched

**Comment by MarkusCool** [comment]
Validated in version v1.1.14093
