### ISSUE TITLE
IDB.Translate.BCP: IterationNumber for Items must be counted in ascending order 

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/powerload-utilities#17]
IterationNumber for Items must be counted in ascending order even when the Revision increases when the IDB.Translate.BCP is creating the BCP package.
Sample: 
GIVEN in items table of IDB:
2 iterations of an item in the IDB, one with Revision=A and Version=1, and the second with Revision=B and Version=2
THEN in the current version of the IDB.Translate.BCP the IterationNumber in the ItemsWrapper.xml for both items is "1".
**Correct would be:**
The ItemsWrapper.xml the IterationNumber for the first iteration (Revision=A) is "IterationNumber =1" and for the second iteration (Revision=B) "IterationNumber =2".
The IterationNumber MUST NOT begin with 1, when the version number increases.
| Revision| Version/IterationNumber | Note |
| - | - | - |
A| 1 |  |
B| 2 | MUST NOT begin with 1 |

(Details can be found on support case #4056)

**Comment by MarkusCool** [comment]
Hi Dean! 
did you meanwhile fix this but it must be merged to the main branch, or should we transfer the task to Wangdu?
Thank you!
Markus

**Comment by wgyalpo** [comment]
I cannot reproduce this issue. For me the result is correct. It may have been fixed earlier.


![Image](https://user-images.githubusercontent.com/43564719/190366188-18246047-aa14-4291-9349-377780ba6530.png)

**Comment by MarkusCool** [comment]
Validated in version v1.1.14093
