### ISSUE TITLE
Implement Folder/Folder links in IDB.Translate.BCP

### ISSUE THREAD

**Issue by kieninj** [coolOrangeLabs/powerload-utilities#20]
table `FolderFolderLinks` is just used for **additional** links between folders (projects). It's not used for parent/child folder relationship.
Folder/Folder links have to be added to bcpIntermediateDatabaseApp

_Originally posted by @kieninj in https://github.com/coolOrangeLabs/bcpIntermediateDatabase/issues/10#issuecomment-563157715_

**Comment by MarkusCool** [comment]
In the IDB there is a table 'FolderFolderLinks' with 'ParentFolderID' and 'ChildFolderID'.
In the attached 'Load_Link.zip' there is a backup of the IDB, that contains the table 'FolderFolderLinks' filled. 
The FolderFolderLink in Vault looks like this:
![FolderFolderLink_Vault](https://user-images.githubusercontent.com/36193155/186169931-275ac8cc-2220-4d0c-8f95-fb2195db6179.png)
[Load_Link.zip](https://github.com/coolOrangeLabs/powerload-utilities/files/9402870/Load_Link.zip)

**Comment by MarkusCool** [comment]
Validated in version v1.1.14093
