### ISSUE TITLE
Table 'TargetVaultCategories' is not filled from IDB.Discover.Vault from a NON-English Vault

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/powerload-utilities#37]
When running the IDB.Discover.Vault against a German Vault the table 'TargetVaultCategories' is not filled, meanwhile the other TargetVault-tables are filled. There is no error message in the log file.

**Comment by MarkusCool** [comment]
Workaround for German Vault:
SELECT E.BaseId AS EntityClassId, C.DisplayName AS Category
FROM dbo.BehaviorClass BC
INNER JOIN dbo.EntityClassBehavior EC ON BC.BehaviorClassId = EC.BehaviorClassID
INNER JOIN dbo.EntityClass E ON EC.EntityClassID = E.EntityClassID
INNER JOIN dbo.CategoryDef C ON EC.BehaviorID = C.CategoryDefId
WHERE BC.DisplayName = '**Kategorie**'
ORDER BY E.BaseId,C.DisplayName

**Comment by wgyalpo** [comment]
Talk with Christian about how to detect Language of the Target Vault.
One option is to set in the ini file the Category in the Target Vault's language.

**Comment by MarkusCool** [comment]
Make the where clause as a OR statement: where 'Category' or 'Kategorie' ...

**Comment by MarkusCool** [comment]
Validated for version Release_24112021 in German environment.
