### ISSUE TITLE
IDB.Analyzer.Inventor (v 1.1.7900) is not filling the 'FileFileRelations' table

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/powerload-utilities#42]
The IDB.Analyzer.Inventor (v 1.1.7900) is not filling the 'FileFileRelations' table. Number of missing references are set to 145 (for my data set), which is not correct. A lot of files are marked as "ERROR: Unknown reference:", which are not 'unknown references'.

Version 1.1.7796 war handling this correct and just found 2 missing references.

Steps to reproduce:

1. Make sure you have a IDB
2. Make sure you have a filestore. Unpack Legacy Filestore.zip, if you don't have a sample filestore
2. Configure in IDB.Analyzer.Common.ini that the correct ipj is used
3. Configure in IDB.Core.ini that the correct IDB is used
4. Start IDB.Analyzer.Inventor  (v 1.1.7900); Result: The 'FileFileRelations' table is **not** filled
5. Start old IDB.Analyzer.Inventor  (v 1.1.7796) with same settings; Result: The 'FileFileRelations' table is filled

**Comment by MarkusCool** [comment]
[IDB.Analyzer.Inventor.log](https://github.com/coolOrangeLabs/powerload-utilities/files/7021917/IDB.Analyzer.Inventor.log)
![DLG-IDBAnalyzerInventor_7900](https://user-images.githubusercontent.com/36193155/130243824-5394dc67-f81e-4169-8db0-971e59f90967.png)

**Comment by MarkusCool** [comment]
I am not able to upload a ZIP here. 
The Legacy Filestore.zip can be downloaded from: [https://my.hidrive.com/lnk/c4ilnbHT]

**Comment by wgyalpo** [comment]
Hi @DeanBrisson,
I want to ask you if you could give a look at this issue since the last changes were from your side some time ago. Just saying this because it might be faster for you to find the issue and fix it than me. Let me know if this is fine with you.
