### ISSUE TITLE
add powerExtractor functionality

### ISSUE THREAD

**Issue by christiangessner** [coolOrangeLabs/powerload-utilities#64]
https://github.com/coolOrangeProjects/SPXFLOW-Vault-Extractor/tree/powerExtractor/Files/powerExtractor

**Comment by MarkusCool** [comment]
- seperate repro
- build pipeline
- build version 2020, 2021, 2022, 2023
- make msi

**Comment by wgyalpo** [comment]
Implemented here: https://github.com/coolOrangeLabs/powerExtractor
