### ISSUE TITLE
Analyse der Referenzen nur über Dateiname (ResolveByFileNameOnly) 

### ISSUE THREAD

**Issue by kieninj** [coolOrangeLabs/powerload-utilities#65]
Required by customer Beumer (FAM) for migrating data from ProFile to Vault.
Details see:

- [x] Inventor References (https://github.com/coolOrangeProjects/FAM/issues/2)
- [x] AutoCAD Xrefs (https://github.com/coolOrangeProjects/FAM/issues/11)
- [x] Inventor OLE References

**Comment by MarkusCool** [comment]
Integrated into powerLoad_v1.1.14316
