### ISSUE TITLE
IDB.Load.Files crashes while computing checksum if file is unreadable

### ISSUE THREAD

**Issue by miltcapsimalis** [coolOrangeLabs/powerload-utilities#71]
The checksum calculation code in IDB.Load.FIle opens a FileStream for each file. This throws exceptions for various reasons including the file being in use. 

```
public static int CalcChecksum(string filename)
        {
            using (FileStream stream = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.Read, ChunkSize))
                return CalcCrc32(stream);
        }


```
This code need to catch exceptions and move on.

> System.IO.IOException
>   HResult=0x80070780
>   Message=The file cannot be accessed by the system.
> 
>   Source=mscorlib
>   StackTrace:
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
>    at IDB.Core.File.Checksum.CalcChecksum(String filename) in C:\Users\Milt\Documents\GitHub\powerload-utilities\IDB\Core\File\Checksum.cs:line 82

**Comment by MarkusCool** [comment]
Steps to reproduce:
1. Make sure that a DWG is in the filestore to import
2. Open a DWG file with AutoCAD (Mechanical)
3. Run IDB.Load.Files on filestore with the DWG file.
Result: The IDB.Load.Files crashes with the stated error above.
Expected result, like Milt suggested: 

 1. Catch the exception
 2. Log the issue as a warning in the logfile, recording the filename and noting that the checksum in the IDB will be invalid
 3. return -1 for the checksum
 4. move on without crashing

**Comment by MarkusCool** [comment]
Validated in version v1.1.14093
