### ISSUE TITLE
Add a switch in the settings to allow long path just for analysis

### ISSUE THREAD

**Issue by wgyalpo** [coolOrangeLabs/powerload-utilities#73]
This switch when true allows to import files and folders in the database which has length longer than 260 characters.

Tasks
- Change the Create.IDB.sql default for LocalFullFilename from 260 to max
- Add a switch 'AllowLongPathForAnalysis' in the IDB.Load.Files.Behaviors.ini with default false under a new section 'Danger Zone'

**Comment by MarkusCool** [comment]
In Version v1.1.14093 the new switch 'AllowLongPathForAnalysis' is integrated, but in the Create.IDB.sql 'LocalFullFilename' is still set to 260.

**Comment by MarkusCool** [comment]
When a file with a long path is iserted, it is modified to a short file path with "~" character. So we can keep the lenth for 'LocalFullFilename' at 260 characters.
