### ISSUE TITLE
Allow list of files in txt file for adding to IDB 

### ISSUE THREAD

**Issue by wgyalpo** [coolOrangeLabs/powerload-utilities#75]
New settings in the IDB.core.ini 'ImportFilesFromTextFile' is introduced for adding list of files in the txt file to the IDB.
When this setting is not empty, then only from this list is added to the database. Otherwise, when empty, which is the default case, then the importpath settings will be used for importing the files.

**Comment by MarkusCool** [comment]
There is still an error when the file in the text file is quoted:
![grafik](https://user-images.githubusercontent.com/36193155/192727611-085bbd74-0c7b-476d-acb1-03501e174be8.png)
[Import.txt](https://github.com/coolOrangeLabs/powerload-utilities/files/9662920/Import.txt)

**Comment by MarkusCool** [comment]
Validated and documented in version v1.1.14316.
