### ISSUE TITLE
Change default Lifecycle State in IDB.Load.Files to Released

### ISSUE THREAD

**Issue by miltcapsimalis** [coolOrangeLabs/powerload-utilities#81]
There is rarely a reason to bulk-load files in WIP! If someone is working on them they should load them. If they are part of a bulk load they are almost by definition Released. The only other case would be if someone had an Archived state or some other state that they want to apply to a special set of files they are loading into an otherwise active Vault.

**Comment by MarkusCool** [comment]
You can set the default for the state for the files that are imported into the IDB by changing attribute "LifeCycleState" in config file IDB.Load.Files.Behaviors.ini. But be careful! If you forget to change the state of the files that should not be released, you might run into issues after the import into Vault. When you then change the state from "Released" to "WIP" the revision lable increases, which you might not want. This happend already in a project.

**Comment by miltcapsimalis** [comment]
Has anyone ever loaded a full vault and actually wanted the files set to wip ?
That explains why you’ve had problems with bumping the revision “by accident” and explains why the default should be released. I can’t think of one time when anyone wanted to load a whole Vault in WIP, can you?

**Comment by MarkusCool** [comment]
I cannot remember anyone who wanted to import all files as "Released". 
But as said you can change the default import state in the IDB.Load.Files.Behaviors.ini.
